name: Build and Deploy ASP.NET Core App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: nguyenhauweb  # Tên của Azure App Service
  AZURE_WEBAPP_PACKAGE_PATH: './publish'  # Đường dẫn đến thư mục xuất bản

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Build and Publish
        run: |
          dotnet restore ./CurrentTimeService.sln
          dotnet publish ./CurrentTimeService/CurrentTimeService.csproj --configuration Release --output './publish'
          ls -la ./publish  # Kiểm tra nội dung thư mục publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: publish

      - name: List contents
        run: ls -la  # Kiểm tra nội dung thư mục hiện tại

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: './publish'  # Đảm bảo đường dẫn chính xác tới thư mục publish
